### ISSUE TITLE
Add TVMaze feed

### ISSUE THREAD

**Issue by drauch** [RoliSoft/RS-TV-Show-Tracker#5]
After the shutdown of TVRage, many users switch to TVMaze http://www.tvmaze.com/ . RSTVShowTracker should probably support this API as well, see http://www.tvmaze.com/api for more information.

I'm a developer, and would even spend some time to implement it myself - any help appreciated. Unfortunately, the link in the settings dialog to "how to write own plugin for a new feed" does bring up a 404 error in the browser :-/

**Comment by RoliSoft** [comment]
The owners of the site contacted me in order to cooperate, and I obtained an API key from them already, however it has not yet been implemented due to lack of time.

Any change other than small bug fixes will most likely not be implemented until around 2016 Q2, as I'm quite busy with my thesis and research until I graduate.

The link you mention was supposed to contain a tutorial on writing news grabbers, something slightly irrelevant, as show data parsers are much more complicated than just generating an RSS link for the reader. Regardless, was never written.

**Comment by drauch** [comment]
Can you point out an example of a data parser using a similar API (I guess it is some kind of REST-based API?) The API key is already checked into the repo? If it is not TOO much work, I guess I could do it over X-mas holidays...

**Comment by RoliSoft** [comment]
Checked the emails with the owner, and it seems I incorrectly remember as I was not given an API key since one is not required to access the API.

There are no tutorials or any example parsers available other than the actual parsers themselves, however they are somewhat documented, and if you go through them, you should get a grip on how it works.

You can find these parsers here: https://github.com/RoliSoft/RS-TV-Show-Tracker/tree/master/Parsers/Guides/Engines

I would recommend looking at TMDb, IMDb and Freebase, since these process JSON APIs, similar to what TVmaze exposes.

You should try and map as many properties as you can, however if something is not available, just leave it empty, or in some cases just guesstimate. For example, if runtime is not available, I set 30 minutes, which would be the average between 20 and 40.

**Comment by drauch** [comment]
Are you using VS 2015 already? Unfortunately, your project won't load, see https://stackoverflow.com/questions/33982184/how-to-use-t4-with-vs2015-microsoft-texttemplating-targets-files-not-found Any ideas?

**Comment by RoliSoft** [comment]
I migrated as soon as it became available. In order to load the project, you'll need to install VS SDK and Modeling SDK first. This is not new, it applies to every version of VS you want to load the project in.

See: https://tvshowtracker.net/#source

**Comment by drauch** [comment]
Thanks, for the quick reply. Found it out myself in the meantime.

**Comment by drauch** [comment]
Another question though, sorry for spamming: unit testing fails with "Could not load file or assembly `Microsoft.WindowsAPICodePack.Shell, Version=1.0.0.0, Culture=neutral, PublicKeyToken=...' or one of its dependencies. The system cannot find the file specified.

I guess I have to tell NUnit somehow to use the Dependencies folder? I'm using R# unit test runner, if it matters. ;-)

**Comment by RoliSoft** [comment]
Last time I had dependency issues with R#'s test runner, I had to go into settings and enable something along the lines of "copy shadow assemblies" [or rather, don't copy them?] under the R#/NUnit settings.

See if toggling that helps.

**Comment by drauch** [comment]
Unfortunately, neither this nor any other option on this option dialog helped (probably in the long run it is best to go for NuGet dependencies).

Still, have finished my draft, unfortunately, I couldn't execute the tests...however, see https://github.com/RoliSoft/RS-TV-Show-Tracker/pull/6 . Let's discuss there what steps to take next (which manual tests I have to do, etc.).

Thanks for the dev support! Really looking forward to RS TV Show Tracker with TVmaze support!

**Comment by RoliSoft** [comment]
NuGet was not a thing when I very first started working on the application. :) I will most likely be moving them over to NuGet as I get enough free time to reorganize everything.

I'll check your pull request and if it works, I'll accept it into master.

**Comment by RoliSoft** [comment]
Done. You can either pull the commits and compile it for yourself, or download the nightly from here: https://tvshowtracker.net/#download

Thank you for your contribution!
